name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Build
      run:  |
        echo $PATH
        echo ls
        cd ./PS_Template/PS.Template.API/PS.Template.API/
        dotnet build PS.Template.API.csproj
    - name: Test
      run:  |
        cd ./PS_Template/PS.Template.API/PS.Template.ApplicationTest/ 
        dotnet test PS.Template.ApplicationTest.csproj
